In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [3]:
connection = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [22]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-07-21 20:45:28.261459
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-07-21 20:45:28.261459
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-07-21 20:45:28.261459

In [23]:
connection.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR, 
        MAKTX VARCHAR, 
        WERKS VARCHAR, 
        MAINS VARCHAR, 
        LABST VARCHAR, 
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [25]:
connection.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [6]:
resultado = connection.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-07-21 20:36:01.659719
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-07-21 20:36:01.659719
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-07-21 20:36:01.659719
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-07-21 20:45:28.261459
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-07-21 20:45:28.261459
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-07-21 20:45:28.261459

In [5]:
connection.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [7]:
connection.close()